name:                haskell-brainfk
version:             0.1.0.0
github:              "yuki2501/haskell-brainfk"
license:             BSD3
author:              "yuki2501"
maintainer:          "yuki2501@protonmail.com"
copyright:           "2021 yuki2501"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/yuki2501/haskell-brainfk#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec
- text
- monad-skeleton
library:
  source-dirs: src

executables:
  haskell-brainfk-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-brainfk

tests:
  haskell-brainfk-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-brainfk
